export const SET_MOVIE_SELECTED = "SET_MOVIE_SELECTED";
export const SET_THEATERS_SELECTED = "SET_THEATERS_SELECTED";
export const SET_THEATER_ID_SELECTED = "SET_THEATER_ID_SELECTED";
export const SET_TICKET_PRICE_SELECTED = "SET_TICKET_PRICE_SELECTED";
export const SET_THEATER_FRANCHISE_SELECTED = "SET_THEATER_FRANCHISE_SELECTED";