export const GET_LIST_MOVIE = 'GET_LIST_MOVIE'
export const GET_LIST_MOVIE_PAGINATION = 'GET_LIST_MOVIE_PAGINATION'
export const GET_DETAIL_MOVIE = 'GET_DETAIL_MOVIE'
export const GET_LIST_MOVIE_BY_DATE = 'GET_LIST_MOVIE_BY_DATE'