export const GET_USER = 'GET_USER'
export const POST_USER = 'POST_USER'
export const LOG_OUT = 'LOG_OUT'
export const GET_TYPE_USER = 'GET_TYPE_USER'
export const GET_INFO_USER_LOGIN = 'GET_INFO_USER_LOGIN'