export const SET_THEATERS = "SET_THEATERS";
export const SET_THEATER_ID = "SET_THEATER_ID";
export const SET_MOVIE_LIST = "SET_MOVIE_LIST";
export const SET_THEATER_FRANCHISES = "SET_THEATER_FRANCHISES";